// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLiqpdzE2X57n39dbURYY0lAoPhDKvhbQ',
    appId: '1:707577937763:web:ddd97dd21917bca9f85d56',
    messagingSenderId: '707577937763',
    projectId: 'lesson66-e0c3e',
    authDomain: 'lesson66-e0c3e.firebaseapp.com',
    storageBucket: 'lesson66-e0c3e.appspot.com',
    measurementId: 'G-QHPMJY05W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUQzviZANpeTc2dtACHPdDlPtVxX1NJF4',
    appId: '1:707577937763:android:cecf4b8ea1623e1df85d56',
    messagingSenderId: '707577937763',
    projectId: 'lesson66-e0c3e',
    storageBucket: 'lesson66-e0c3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQy1Q6YnhMHP0neAhANSC6gLtzn4XydEI',
    appId: '1:707577937763:ios:eb07e0b7399e0fd7f85d56',
    messagingSenderId: '707577937763',
    projectId: 'lesson66-e0c3e',
    storageBucket: 'lesson66-e0c3e.appspot.com',
    iosBundleId: 'com.example.fayrbaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQy1Q6YnhMHP0neAhANSC6gLtzn4XydEI',
    appId: '1:707577937763:ios:eb07e0b7399e0fd7f85d56',
    messagingSenderId: '707577937763',
    projectId: 'lesson66-e0c3e',
    storageBucket: 'lesson66-e0c3e.appspot.com',
    iosBundleId: 'com.example.fayrbaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLiqpdzE2X57n39dbURYY0lAoPhDKvhbQ',
    appId: '1:707577937763:web:0355e9371cf5db87f85d56',
    messagingSenderId: '707577937763',
    projectId: 'lesson66-e0c3e',
    authDomain: 'lesson66-e0c3e.firebaseapp.com',
    storageBucket: 'lesson66-e0c3e.appspot.com',
    measurementId: 'G-RG17EN5GPG',
  );
}
